<?php

namespace Ben\MyCarParkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarParkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarParkRepository extends EntityRepository
{
}
