<?php

namespace Ben\MyCarParkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StayRepository extends EntityRepository
{
}
